version: '2'
services:
  gobgp:
    image: nstgt/docker-gobgp
    container_name: gobgp
    command: /usr/local/bin/gobgpd -f /root/gobgpd.conf
    volumes:
      - ${PWD}/gobgp:/root
    networks:
      br01:
        ipv4_address: 10.0.1.10
  bgpbully:
    image: nstgt/bgpbully
    container_name: bgpbully
    command: /usr/local/bin/bgpbully -f /bgpbully/config.yaml
    volumes:
      - ${PWD}/bgpbully:/bgpbully
    networks:
      br01:
        ipv4_address: 10.0.1.20
networks:
  br01:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
